### ISSUE TITLE
Is the creation of blockies only available on Client side? 

### ISSUE THREAD

**Issue by yiytan92** [download13/blockies#10]
Is there anyway I can generate blockes on the server, and upload the image somewhere for use on the client?

**Comment by download13** [comment]
Not at the moment. I'm actually going to bump the major version in a bit while adding a pull request from a while back.

I can add the ability to pass in a canvas as an option in the next version, then you can include the node canvas library, just pass in an instance, then do whatever you want with the data when it's done drawing the icon.

**Comment by download13** [comment]
The README now has an example for how to use this with node.

**Comment by yiytan92** [comment]
Thank you.
